# Configure your application
shared: &shared
  # Configure your app's name
  app_name: Fugacious

  # This establishes the maximum number of hours that a message can be active.
  max_retention_hours: 720 # 30 days

  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  # Make sure the secret is at least 30 characters and all random,
  # no regular words or you'll be exposed to dictionary attacks.
  # You can use `rake secret` to generate a secure secret key.
  secret_key_base: f96a2462114e5687c02ee262895f4d3c556d9dbacc5aaf54ea33da31a84970eade80ae9ed4becb5305bdffea1524725a3f09269a496bbe4f90698ccc4ae15e92

development:
  <<: *shared

test:
  <<: *shared

# Uncomment and update these values if deploying to cloud.gov
# cloud.gov:
#   <<: *shared
#   secret_key_base: '' # rake secret
#   max_retention_hours: 24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  app_name: <%= ENV['APP_NAME'] %>
  max_retention_hours: <%= ENV['MAX_RETENTION_HOURS'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
